### ISSUE TITLE
Not Found Error

### ISSUE THREAD

**Issue by manoyes** [sharelatex/docstore-sharelatex#6]
**UPDATE**: I tried downloading the source project, and all non-TeX files download correctly (images and the like) but `.tex` and `.cls` files (for example) are not included.

I updated to the latest version of sharelatex using the commands in the wiki from a very old version (like last August), before the real-time repo was added:

```
git pull
npm install
grunt install
grunt update:all
```

There were no errors during the update process.

I can start the webserver, login and view projects, but every time I try to open a file I get an error message. The full log output from opening multiple files is shown below.

![error](https://cloud.githubusercontent.com/assets/1971456/6790811/56742670-d178-11e4-83ad-c923225441f3.png)

https://gist.github.com/manoyes/f14d02a90512f83125fb

I checked my `settings.coffee` file, and my `data` and `tmp` directories still point to the same location they did before.

**Comment by jpallen** [comment]
Are you using the master branch? This has some changes in the docstore where we've updated the Mongo schema to store documents in a different place. If you use the release branch instead, the old schema is used.

We're working on a migration script that needs some more testing before you can switch over the master branch. We recommend only running the release branches for this sort of reason.
